### ISSUE TITLE
Attempting to export from an Importer that has failed Entries throws error

### ISSUE THREAD

**Issue by bkiahstroud** [samvera-labs/bulkrax#170]
Error occurs here: https://github.com/samvera-labs/bulkrax/blob/master/app/parsers/bulkrax/csv_parser.rb#L101 

Because the `Entry` failed to create a Work, attempting to look up a Work's id through the `Entry#identifier` fails with a undefined method on nil error. 

```ruby
ActiveFedora::SolrService.query(query, fl: 'id', rows: 1)
=> []
ActiveFedora::SolrService.query(query, fl: 'id', rows: 1).first
=> nil
ActiveFedora::SolrService.query(query, fl: 'id', rows: 1).first['id']
=> undefined method `[]' for nil:NilClass
```

**Proposed fix:** Before running the exporter, filter out the Importer's entries that contain errors. 

**NOTE:** The above proposed fix is a little band-aid-y. Consider a more long-term solution.

**Comment by geekscruff** [comment]
I'm not sure I'd say that's band-aid-y ... because we're exporting WORKS, we only want the entries that will have works attached, hence filtering out errors is the obvious way to do that.

**Comment by bkiahstroud** [comment]
Commit to proposed fix: https://github.com/samvera-labs/bulkrax/pull/68/commits/ea029495b349c983dd53a69dc1567b31285aca55
