### ISSUE TITLE
Is it possible to import multiple keywords and multiple creators with CSV importer?

### ISSUE THREAD

**Issue by tedstrauss** [samvera-labs/bulkrax#215]
I'm trying to use Bulkrax to import data for works with multiple entries of the creator field and keyword field.
Is it possible to that with this package?
Is there any documentation, or code reference to help figure it out?

**Comment by dlim87** [comment]
https://github.com/samvera-labs/bulkrax/wiki/Configuration#field-mappings You want to use the `split` property for that field, in which case it will import it as multi-valued, splitting on the specified character

**Comment by naseer-phaedra** [comment]
@dlim87  do i need to do something like this

config.field_mappings = {
    "Bulkrax::CsvParser" => {
      "contributor" => { from: ["contributor"] },
      "creator" => { from: ["creator"], split: true },
      "keyword" => { from: ["keyword"], split: true },
      "date_created" => { from: ["date"] },
      "description" => { from: ["description"] },
      "identifier" => { from: ["identifier"] },
      "language" => { from: ["language"], parsed: true },
      "publisher" => { from: ["publisher"] },
      "related_url" => { from: ["relation"] },
      "rights_statement" => { from: ["rights"] },
      "license" => { from: ["license"], split: "\|" }, # some characters may need to be escaped
      "source" => { from: ["source"] },
      "subject" => { from: ["subject"], parsed: true },
      "title" => { from: ["title"] },
      "resource_type" => { from: ["type"], parsed: true },
      "remote_files" => { from: ["thumbnail_url"], parsed: true }
    }
  }

**Comment by dlim87** [comment]
You need to specify the character to split on, with it being escaped. E.g. `"creator" => { from: ["creator"], split: "\|" },`

**Comment by naseer-phaedra** [comment]
Thanks, let me try this.

**Comment by naseer-phaedra** [comment]
Thanks @dlim87  it worked.

**Comment by dlim87** [comment]
In that case, I'm going to close this issue
