### ISSUE TITLE
Bulkrax Importer does not import csv data with file column

### ISSUE THREAD

**Issue by naseer-phaedra** [samvera-labs/bulkrax#263]
I'm trying to import csv data via bulkrax importer it imports successfully all work entries but when i add a file column in csv file it does not import any work or collection entry.  I have placed files folder relative to csv file but it neither imports data nor files. Can you please help me figure out what i am doing wrong?

**Comment by bkiahstroud** [comment]
Hi @naseer-phaedra. On the importer's show page (`/importers/:id`), are you seeing any errors on the importer (above "Total Works") or on any of the importer's work entries (in the table at the bottom of the page)?

**Comment by hammad417** [comment]
Hi @bkiahstroud no its not showing errors
it just shows
Frequency: PT0S

Parser klass: Bulkrax::CsvParser

Limit:

Parser fields:
rights_statement:
override_rights_statement: 0
file_style: Specify a Path on the Server
import_file_path: spec/fixtures/csv/metadata.csv
Field mapping: Toggle

contributor: {"from"=>["contributor"]}
creator: {"from"=>["creator"], "split"=>true}
keyword: {"from"=>["keyword"], "split"=>true}
date_created: {"from"=>["date"]}
description: {"from"=>["description"]}
identifier: {"from"=>["identifier"]}
language: {"from"=>["language"], "parsed"=>true, "split"=>true}
publisher: {"from"=>["publisher"]}
related_url: {"from"=>["relation"]}
rights_statement: {"from"=>["rights"]}
license: {"from"=>["license"], "split"=>"|"}
source: {"from"=>["source"]}
subject: {"from"=>["subject"], "parsed"=>true}
title: {"from"=>["title"]}
resource_type: {"from"=>["type"], "parsed"=>true}
remote_files: {"from"=>["thumbnail_url"], "parsed"=>true}

**Comment by naseer-phaedra** [comment]
Hi @bkiahstroud no its not showing errors
it just shows
Frequency: PT0S

Parser klass: Bulkrax::CsvParser

Limit:

Parser fields:
rights_statement:
override_rights_statement: 0
file_style: Specify a Path on the Server
import_file_path: spec/fixtures/csv/metadata.csv
Field mapping: Toggle

contributor: {"from"=>["contributor"]}
creator: {"from"=>["creator"], "split"=>true}
keyword: {"from"=>["keyword"], "split"=>true}
date_created: {"from"=>["date"]}
description: {"from"=>["description"]}
identifier: {"from"=>["identifier"]}
language: {"from"=>["language"], "parsed"=>true, "split"=>true}
publisher: {"from"=>["publisher"]}
related_url: {"from"=>["relation"]}
rights_statement: {"from"=>["rights"]}
license: {"from"=>["license"], "split"=>"|"}
source: {"from"=>["source"]}
subject: {"from"=>["subject"], "parsed"=>true}
title: {"from"=>["title"]}
resource_type: {"from"=>["type"], "parsed"=>true}
remote_files: {"from"=>["thumbnail_url"], "parsed"=>true}

**Comment by naseer-phaedra** [comment]
@bkiahstroud when i remove file column from csv file and set file path in importer it imports all works and collections without any error.

**Comment by bkiahstroud** [comment]
>  I have placed files folder relative to csv file

@naseer-phaedra Does this ^ mean you have already put the files you are intending to import on the server, similarly to how [the documentation](https://github.com/samvera-labs/bulkrax/wiki/CSV-Importer#files-location) describes?

**Comment by naseer-phaedra** [comment]
@bkiahstroud  yes. Actually i have setup hyku project with docker and this gem is being used for imports and exports via admin dashboard and i have followed the given docs for bulkrax imports.

**Comment by naseer-phaedra** [comment]
@bkiahstroud i have placed the files and csv file like this in my project. 
spec/fixtures/csv/data.csv
spec/fixtures/csv/files/sample.pdf

**Comment by bkiahstroud** [comment]
@naseer-phaedra Is the file column in your CSV named `remote_files`? If so, can you try renaming it to just `files` and trying the import again? 

`remote_files` is used for importing files from the web, so that column would hold urls instead of filenames.

**Comment by naseer-phaedra** [comment]
@bkiahstroud no the column name is file. but i have also tried with column name files which imports work entries with status failed and gives Runtime error "RSolr::Error::Http - 400 Bad Request"

**Comment by bkiahstroud** [comment]
@naseer-phaedra Unless you've added a custom [field mapping](https://github.com/samvera-labs/bulkrax/wiki/Configuration#field-mappings), `files` should be the proper column name.

It sounds like Solr might not be running properly in your Hyku application. I recommend asking about the Solr 400 error in [the #hyku channel of the official Samvera Community's Slack](https://samvera.slack.com/archives/C7E4KK8ER); the community knows far more about Solr than I do.

In the meantime:
1. Are you using [dory](https://github.com/FreedomBen/dory)?
2. In your `docker-compose.yml` file, does your solr container have a virtual host? (`solr.environment.VIRTUAL_HOST`)
3. If the answers to 1 and 2 above are yes, are you able to navigate to the virtual host in your browser? (`http://<VIRTUAL_HOST>/solr`)

**Comment by alishaevn** [comment]
closing this out as there's been no response in over 18 months.
