### ISSUE TITLE
Entry show page does not have Item Link

### ISSUE THREAD

**Issue by dlpierce** [samvera-labs/bulkrax#267]
When viewing an entry after running an import (CSV in this case if it matters), the show page says "Item has not yet been imported successfully" instead of a link to the imported work. This seems to be caused by use of last_succeeded_at which seems like it was removed from use in #237

**Comment by aploshay** [comment]
@dlpierce I think this issue may be resolved as written, by recent bulkrax updates; although I'm still seeing "Item has not yet been imported successfully" (even though it has), I'm now _also_ seeing a working link to the item

**Comment by alishaevn** [comment]
@dlpierce @aploshay this issue should be resolved now. (we're currently on `v3.4.0`) please reopen with updated details if the issue still shows for you!
