### ISSUE TITLE
CSV Imports with Collection titles that have colon, semi-colon, or pipe characters never succeed

### ISSUE THREAD

**Issue by bkiahstroud** [samvera-labs/bulkrax#278]
The two `.split(/\s*[:;|]\s*/)` in [these methods](https://github.com/samvera-labs/bulkrax/blob/82dffb267c382c3f096c1337ee09a084c9f0335e/app/models/bulkrax/csv_entry.rb#L132-L147) cause importers importing collections with any of those characters in their titles to [spin endlessly](https://github.com/samvera-labs/bulkrax/blob/82dffb267c382c3f096c1337ee09a084c9f0335e/app/jobs/bulkrax/import_work_job.rb#29-31). Collections have their own [collection_field_mapping](https://github.com/samvera-labs/bulkrax/blob/82dffb267c382c3f096c1337ee09a084c9f0335e/app/models/bulkrax/csv_entry.rb#L40) that only accepts a string (and no `split` argument).

`Bulkrax.collection_field_mapping`s should accept a `split` argument to customize the character(s) that CSV Collection imports split on.

**Comment by alishaevn** [comment]
collections are now imported using their own row insteadl of a "collection" column header. (that was deprecated in `v3.0.0`)
