### ISSUE TITLE
Object, multiple objects and nested object field mapping

### ISSUE THREAD

**Issue by alishaevn** [samvera-labs/bulkrax#296]
# Related to
https://gitlab.com/notch8/britishlibrary/-/issues/58

# Summary
bulkrax field mapping needs to be updated to handle more complexity

# Acceptance criteria
Bulkrax can:
- [x] handle an object
- [x] handle multiple objects
- [x] handle an object with a property that has multiple values
- [x] handle csv headings that are prepended or appended with numerators

**Comment by orangewolf** [comment]
this was completed
