### ISSUE TITLE
“Update and Re-import (update metadata only)” re-imports and adds unchanged files

### ISSUE THREAD

**Issue by jwhitney** [samvera-labs/bulkrax#299]
I’m using the CSV importer to import objects described in a metadata.csv on the local server, with the metadata.csv pointing to files in a files/ subdirectory.

The metadata is later updated with info that we generate elsewhere. 

When I edit the importer and choose “Update and re-import (update metadata only)”, the metadata is updated as expected but files are re-imported and added to works as duplicate files, although the files have not changed. 

The wiki says only new files will be added with a metadata-only update. Is this a bug, or is the wiki just out of date & this is how the importer is intended to work?  ie. always import any files listed in the CSV.

**Comment by orangewolf** [comment]
@jasoncorum that is a bug. it is expected that it would only add new files. I'm wrapping up a bunch of work on Bulkrax this week. I'll test this issue and see what happens for me here and report back.

**Comment by orangewolf** [comment]
@jwhitney we resolved this in Bulkrax 1.0.2. I'm going to close this, but feel free to reopen if upgrading doesn't resolve it for you.
