### ISSUE TITLE
UI Bugs

### ISSUE THREAD

**Issue by ShanaLMoore** [samvera-labs/bulkrax#350]
**Demo:** https://share.getcloudapp.com/mXuKDkYK

**Steps to reproduce:** 
Create an importer
Go to the importers index page
Click into the created importer
Click the back button (see screenshot)
<img width="1414" alt="Screen Shot 2021-09-10 at 3 43 23 PM" src="https://user-images.githubusercontent.com/10081604/132925111-ecc1b67d-349a-43e8-aca9-2c601779b10f.png">

Notice the following UI issues:
<img width="1182" alt="Screen Shot 2021-09-10 at 3 13 43 PM" src="https://user-images.githubusercontent.com/10081604/132924874-326e152e-c62f-480a-b85b-ec44f4f7f63d.png">

Also this: 
<img width="721" alt="Screen Shot 2021-09-30 at 11 21 46 AM" src="https://user-images.githubusercontent.com/10081604/135510053-499c0d09-6743-494e-a3c2-7d5d23ff626b.png">

**Comment by bkiahstroud** [comment]
This is due to the Turbolinks gem and the DataTables jQuery library not playing nice with each other

**Comment by ShanaLMoore** [comment]
https://github.com/samvera-labs/bulkrax/pull/414
