### ISSUE TITLE
Remove support / add feature flipper for importing Collections by title when importing Works

### ISSUE THREAD

**Issue by bkiahstroud** [samvera-labs/bulkrax#368]
The ability to import Collection with metadata was added recently (https://github.com/samvera-labs/bulkrax/pull/364). This is the preferred method of importing Collections. In order to simplify the method of importing Collections for both users and maintainers, the ability to import Collections by title on Work rows should be removed. 

Example: 

| model | source_identifier | title | collection |
| --- | --- | --- | --- |
| Work | work_1 | First Work | Parent Collection |

**Current behavior:** 

Before the work is created, a collection titled "Parent Collection" will be created. Once both the Work and the Collection have been created, the Work will be added as a member of the Collection. 

**Expected behavior:** 

The `collection` column will not create any Collections. Instead, Collections should be imported using their own rows, and relationships should be declared using identifiers.

**Comment by alishaevn** [comment]
importing collections using the "collection" header was deprecated in v3.0.0
https://github.com/samvera-labs/bulkrax/wiki/CSV-Importer#deprecated-in-v300
