### ISSUE TITLE
collection_field_mapping support v.2.0

### ISSUE THREAD

**Issue by ShanaLMoore** [samvera-labs/bulkrax#401]
Until support for collection_field_mapping is deprecated, we need to support this configuration. 

With the current changes, the importer will fail because the collection doesn't have a work identifier. 

In the older version of bulkrax, there were [default settings](https://github.com/samvera-labs/bulkrax/blob/v1.0.0/app/parsers/bulkrax/csv_parser.rb#L56-L69) when creating a collection.

Bulkrax v2.0 [removes](https://github.com/samvera-labs/bulkrax/blob/fbfe3960e444babfde2e84f017ab98775e34525b/app/parsers/bulkrax/csv_parser.rb#L73-L86) the default settings. Therefore when the entry checks for missing required keys, an exception is raised.

**Comment by dolsysmith** [comment]
Hi there -- 

Using either the to-be-deprecated configuration (with `collection_field_mapping`) or the parent-child configuration, Is it possible to import works into an existing collection that was created in the UI? For a collection created in the UI, I have the minted object ID (present in the URI), but I can't tell from the documentation whether Bulkrax can match on that ID, or if it needs a `source_identifier` for the collection, which I cannot provide in the UI. We are on Hyrax version 2.9.5. 

Thanks for your help!

**Comment by bkiahstroud** [comment]
Hi @dolsysmith. It is possible to import works into an existing collection using the collection's ID with the parent-child configuration. You would simply put the ID in the same column that you would put the `source_identifier`. 

For example, if you have configured your parent column to be called `parents`, your CSV would look something like this: 

| title | parents |
| --- | --- |
| My Imported Work | collection-id |

There are [more examples in the Wiki](https://github.com/samvera-labs/bulkrax/wiki/Configuring-Bulkrax#parent-child-relationship-field-mappings) as well. 

Hopefully that helps! If you have any other questions, let me know.

**Comment by dolsysmith** [comment]
Hi @bkiahstroud, thank you for the response! 

I have followed your example, and the following appears in my `bulkrax.rb` configuration:
```
config.field_mappings['Bulkrax::CsvEntry'] = {
      'parents' => { from: ['parents'], related_parents_field_mapping: true },
      'children' => { from: ['children'], related_children_field_mapping: true },
    }
```
However, when I attempt to import works to the collection whose ID I provide in the `parents` column, the works import without errors but are not added to the collection. When comparing the `Raw Metadata` and `Parsed Metadata` fields on the `importer/entries` page, I can see that the `parents` field is not being mapped to anything. (Not sure if that matters.) 

I am trying to import into a public (not private) collection defined by my user in the UI.

**Comment by bkiahstroud** [comment]
> I can see that the `parents` field is not being mapped to anything

@dolsysmith do you mean that "parents" does not show up at all in raw and/or parsed metadata? Or that it shows up, but the value is empty? 

Also, would you mind showing me your full `config.field_mappings`? (I'm assuming `parents` and `children` are two of several mappings set up in the `bulkrax.rb` config file)

**Comment by dolsysmith** [comment]
Sorry for not being clearer. `parents` shows up as a field in the raw metadata, but not the parsed metadata. 

Here are the field mappings in `bulkrax.rb`:

```
config.field_mappings['Bulkrax::CsvParser'] = {
    "contributor" => { from: ["contributor"] },
    "creator" => { from: ["creator"], split: "; " },
    "date_created" => { from: ["date_created"] },
    "description" => { from: ["description"] },
    "identifier" => { from: ["identifier"] },
    "related_url" => { from: ["related_url"] },
    "rights_statement" => { from: ["rights_statement"] },
    "license" => { from: ["license"] }, 
     "source_identifier" => { from: ["source_identifier"] },
    "keyword" => { from: ["keyword"] },
    "title" => { from: ["title"] },
    "resource_type" => { from: ["resource_type"] },
    "gw_affiliation" => { from: ["gw_affiliation"] },
    "parents" => { from: ["parents"] } 
  }

  config.field_mappings['Bulkrax::CsvEntry'] = {
      'parents' => { from: ['parents'], related_parents_field_mapping: true },
      'children' => { from: ['children'], related_children_field_mapping: true },
    }
```
After unsuccessfully trying to import to a collection, I added `parents` to the `CsvParser` hash above, but it seemed to make no difference.

**Comment by bkiahstroud** [comment]
Ah, I think I see what the problem is. [The documentation](https://github.com/samvera-labs/bulkrax/wiki/Configuring-Bulkrax#parent-child-relationship-field-mappings) was inaccurate -- the relationships field mappings should be assigned to the `CsvParser`, not the `CsvEntry` (I just fixed this in the docs). 

So the `field_mappings` should look like this: 

```ruby
config.field_mappings['Bulkrax::CsvParser'] = {
    "contributor" => { from: ["contributor"] },
    "creator" => { from: ["creator"], split: "; " },
    "date_created" => { from: ["date_created"] },
    "description" => { from: ["description"] },
    "identifier" => { from: ["identifier"] },
    "related_url" => { from: ["related_url"] },
    "rights_statement" => { from: ["rights_statement"] },
    "license" => { from: ["license"] }, 
     "source_identifier" => { from: ["source_identifier"] },
    "keyword" => { from: ["keyword"] },
    "title" => { from: ["title"] },
    "resource_type" => { from: ["resource_type"] },
    "gw_affiliation" => { from: ["gw_affiliation"] },
    'parents' => { from: ['parents'], related_parents_field_mapping: true },
    'children' => { from: ['children'], related_children_field_mapping: true }
  }
```

Sorry for the confusion! Please let me know if that fixes the issue for you.

**Comment by dolsysmith** [comment]
Thank you! Importing a CSV with a collection ID in the `parents` column now adds the items to the collection.

**Comment by bkiahstroud** [comment]
Awesome! Thank you for your comment, we refer users to our Wiki very often so it was really important that that got resolved. Please feel free to open new issues etc. if you have more questions in the future.
