### ISSUE TITLE
unable to delete importers on bulkrax 3+

### ISSUE THREAD

**Issue by alishaevn** [samvera-labs/bulkrax#470]
# summary
somewhere between `v.3.0.0.beta` and `v.3.0.0.beta4` we lost the ability to delete importers.

- an importer trying to be deleted on louisville and pals staging sites resulted in the following error:
``` bash
     PG::ForeignKeyViolation: ERROR: update or delete on table “bulkrax_importer_runs” violates foreign key constraint “fk_rails_c6af228061" on table “bulkrax_pending_relationships” DETAIL: Key (id)=(64) is still referenced from table “bulkrax_pending_relationships”. : DELETE FROM “bulkrax_importer_runs” WHERE “bulkrax_importer_runs”.“id” = $1
```

# sentry error
![image](https://user-images.githubusercontent.com/29032869/164039417-5e73a301-15dc-47bf-beb5-f96aab45b69f.png)

**Comment by orangewolf** [comment]
untested code fix https://share.getcloudapp.com/4guKWZ91

**Comment by ShanaLMoore** [comment]
solved and merged per PR: https://github.com/samvera-labs/bulkrax/pull/487
