### ISSUE TITLE
Collection Titles

### ISSUE THREAD

**Issue by ShanaLMoore** [samvera-labs/bulkrax#476]
# Summary

On the importer and exporter show page, the collections titles no longer render properly.

[ ] Collection titles should display on the importer/exporter show page, if the work is associated with a collection
[ ] We need to update how [we retrieve collection titles](https://github.com/samvera-labs/bulkrax/blob/main/app/views/bulkrax/exporters/show.html.erb#L99-L106), with the Bulkrax 3+ upgrade (which deprecated collection_field_mapping)

Exporter example: 
<img width="1174" alt="Screen Shot 2022-04-19 at 3 52 32 PM" src="https://user-images.githubusercontent.com/10081604/164114290-4f5c3f91-37db-485a-9187-1de197f40fa2.png">

Importer example:
<img width="1241" alt="Screen Shot 2022-04-19 at 3 56 36 PM" src="https://user-images.githubusercontent.com/10081604/164114573-e60fc303-0751-44df-a054-cfc0f9d2374e.png">

**Comment by orangewolf** [comment]
kill the collection column

**Comment by bkiahstroud** [comment]
@ShanaLMoore is this issue resolved by this PR? https://github.com/samvera-labs/bulkrax/pull/480

**Comment by ShanaLMoore** [comment]
yep!
