### ISSUE TITLE
Fix erroring migrations

### ISSUE THREAD

**Issue by bkiahstroud** [samvera-labs/bulkrax#483]
# Summary

Currently, migrations are failing to run in projects that Bulkrax is used in. This is the error: 

```
PG::DuplicateColumn: ERROR:  column "processed_relationships" of relation "bulkrax_importer_runs" already exists
```

# Acceptance Criteria 

- [ ] Migrations can be run in projects without throwing errors 

# Implementation Details 

Guard statements need to be added to recently added migrations (similar to how they exist in [this migration](https://github.com/samvera-labs/bulkrax/blob/main/db/migrate/20201106014204_add_date_filter_and_status_to_bulkrax_exporters.rb))

**Comment by ShanaLMoore** [comment]
https://github.com/samvera-labs/bulkrax/pull/487
