### ISSUE TITLE
Exporter From type field as a required field

### ISSUE THREAD

**Issue by kirkkwang** [samvera-labs/bulkrax#538]
As a user, I should not be able to create an export if the "Export From" source is not filled out.

On `/exporters/new`, when the `Export From` field is selected, a new field with the same name as the selected entry shows up.  That field does not have a required label nor a validation.  The user can create the export without choosing that option which results in an error.
| Current | Should be | And have |
|---|---|---|
|<img width="400" alt="image" src="https://user-images.githubusercontent.com/19597776/170733743-01a7e056-8c5e-4eb2-a751-4bdd49f16706.png">|<img width="400" alt="image" src="https://user-images.githubusercontent.com/19597776/170734152-6c65ba82-ffaa-4748-8e3a-ba4076de760d.png">|<img width="400" alt="image" src="https://user-images.githubusercontent.com/19597776/170734926-9b2947d2-e08a-40e5-b1b5-a54020fa0f35.png">

These changes should be applied to the `Importer`, `Collection`, and `Work Type` options.
NOTE: Screen shots were created by manipulating the DOM through the browser, work has not begun.

Testing instructions:

- [ ] Go to Dashboard > Exporters > New
- [ ] Fill out:
  - [ ] `Name`
  - [ ] `Type of Export`
  - [ ] `Export From`
  - [ ] `Export Format`
- [ ] Check that if `Importer`, `Collection`, or `Work Type` is chosen from the `Export From` dropdown, there is a `required` badge on the label
- [ ] Without selecting anything in `Work Type` (should be on 'Select from the list'), click `Create and Export`
- [ ] Confirm that the `Please select and item in the list.` alert pops up in the `Work Type` field

**Comment by laritakr** [comment]
refer to https://stackoverflow.com/questions/22148080/an-invalid-form-control-with-name-is-not-focusable

solution needs to mimic what is being done in the importer re: hidden fields.
