### ISSUE TITLE
verify depositor presence on imported works

### ISSUE THREAD

**Issue by alishaevn** [samvera-labs/bulkrax#544]
kirk and I both experienced during the bagit parser testing where the initial importing of a work adds a depositor, but roundtripping the work sometimes creates it with a nil depositor.

the roundtripping may not actually be the culprit, but that's the work flow we were in when we experienced the problem.

more investigation needs to be done.

**Comment by ShanaLMoore** [comment]
Thanks for noting the details. On PALS I created an importer and all of those works had a depositor. So I switched to BL and those works have a depositor too. But now seeing your workflow I will update what happens when we round trip shortly.

**Comment by ShanaLMoore** [comment]
Confirming that with BL, the nil depositor happens on round trip. Digging in!
