### ISSUE TITLE
BUG: Attempting to import a FileSet with multiple files just continuously imports the first file.

### ISSUE THREAD

**Issue by bwatson78** [samvera-labs/bulkrax#614]
Steps to reproduce: 

1. From Dashboard, choose Importers > New, then input any Name and Admin Set.
2. Select the CSV Parser. Visibility can be any.
3. Choose to upload a file. I used this ZIP for my debugging: [Archive 2.zip](https://github.com/samvera-labs/bulkrax/files/9192289/Archive.2.zip)
4. The importer, when it finishes, produces two instances of the first image mentioned, not one FileSet with a preservation_master_file and a service_file.

Likely cause: in `app/parsers/bulkrax/csv_parsers.rb`, there is a method that retrieves the path for the files to be imported:
```
# Retrieve the path where we expect to find the files
def path_to_files(**args)
  filename = args.fetch(:filename, '')

  @path_to_files ||= File.join(
    zip? ? importer_unzip_path : File.dirname(import_file_path), 'files', filename
  )
end
```
This method establishes an instance variable for the parser instance itself. This gets called multiple times if there are multiple files to be imported per FileSet. Yet, the `||=` (equal/or) method will set the instance variable the first time around, causing any other files to be processed with this method to be skipped, just returning the first value established. I've noticed that this same method is established for the Bagit Parser, and acts with roughly the same logic.

**Comment by sephirothkod** [comment]
Hi Brad,

Would you be able to let me know which version of bulkrax you are using? Also some screenshots of the entry page in bulkrax showing the raw metadata and parsed metadata would be very helpful. 

bulkrax should be splitting the files on `;` here in `app/models/bulkrax/csv_entry`:

```
    def add_file
      self.parsed_metadata['file'] ||= []
      if record['file']&.is_a?(String)
        self.parsed_metadata['file'] = record['file'].split(/\s*[;|]\s*/)
      elsif record['file'].is_a?(Array)
        self.parsed_metadata['file'] = record['file']
      end
      self.parsed_metadata['file'] = self.parsed_metadata['file'].map do |f|
        next if f.blank?

        path_to_file(f.tr(' ', '_'))
      end.compact
    end

**Comment by bwatson78** [comment]
Hi Braydon, 
Sorry for taking so long to get back to you--stopped for the day right before you replied yesterday. I'm using v4.2.1, below is the screenshot:
![Screen Shot 2022-07-27 at 9 05 08 AM](https://user-images.githubusercontent.com/18330149/181254341-001d857f-5e2e-428f-ac50-bde91265d755.png)

I've actually fixed the issue, I think, within our Hyrax app by overriding the method with the following code: 
```
def path_to_files(**args)
  filename = args.fetch(:filename, '')

  return @path_to_files if @path_to_files.present? && filename.blank?
  @path_to_files = File.join(
      zip? ? importer_unzip_path : File.dirname(import_file_path), 'files', filename
    )
end
```
I'm going to post a PR with that change and rSpec test with it soon.

**Comment by bwatson78** [comment]
PR made: https://github.com/samvera-labs/bulkrax/pull/618

**Comment by alishaevn** [comment]
released in https://github.com/samvera-labs/bulkrax/releases/tag/v4.3.0.
