### ISSUE TITLE
BrowseEverything Loading Isssue

### ISSUE THREAD

**Issue by ShanaLMoore** [samvera-labs/bulkrax#622]
# Summary 
If you select a parser and refresh the page, the function browseEverything() is no longer found. 

# Steps to reproduce:

- [ ] Create a new importer. 
- [ ] Select a csv parser.
- [ ] Click the "add cloud files" button => this should display a modal
- [ ] Cancel the modal. 
- [ ] Refresh the page
- [ ] The parser should still be selected, but try clicking on the "add cloud files" button again => the modal no longer opens

ref: https://github.com/samvera-labs/bulkrax/pull/619

DEMO: 

https://user-images.githubusercontent.com/10081604/182655989-51962b6f-95b3-4f3a-a89e-40f20aab111d.mp4

<img width="1436" alt="Screen Shot 2022-08-03 at 10 28 08 AM" src="https://user-images.githubusercontent.com/10081604/182671705-149aded0-e714-482a-8345-8c652b01638a.png">

**Comment by alishaevn** [comment]
released in https://github.com/samvera-labs/bulkrax/releases/tag/v4.3.0.
