### ISSUE TITLE
Exporter of type "importer" fails with solrizer error in hyrax 3+

### ISSUE THREAD

**Issue by bbpennel** [samvera-labs/bulkrax#699]
Attempting to use an Exporter with "Export From" set to "importer" is failing for us in a Hyrax 3 repository with the following error:

```
Error: NameError - uninitialized constant Solrizer Did you mean? SolrHit

Error Trace:

ruby/2.7.0/gems/bulkrax-4.4.0/app/parsers/bulkrax/csv_parser.rb:237:in `block in set_ids_for_exporting_from_importer'
ruby/2.7.0/gems/bulkrax-4.4.0/app/parsers/bulkrax/csv_parser.rb:233:in `each'
ruby/2.7.0/gems/bulkrax-4.4.0/app/parsers/bulkrax/csv_parser.rb:233:in `set_ids_for_exporting_from_importer'
ruby/2.7.0/gems/bulkrax-4.4.0/app/parsers/bulkrax/csv_parser.rb:208:in `current_record_ids'
ruby/2.7.0/gems/bulkrax-4.4.0/app/parsers/bulkrax/csv_parser.rb:247:in `create_new_entries'
ruby/2.7.0/gems/bulkrax-4.4.0/app/models/bulkrax/exporter.rb:17:in `create_from_importer'
ruby/2.7.0/gems/bulkrax-4.4.0/app/models/bulkrax/exporter.rb:25:in `export'
ruby/2.7.0/gems/bulkrax-4.4.0/app/jobs/bulkrax/exporter_job.rb:9:in `perform'
```

This appears to be caused by the removal of Solrizer in hyrax 3, which is still used here:
https://github.com/samvera-labs/bulkrax/blob/main/app/parsers/bulkrax/csv_parser.rb#L237

The recommended remediation solr_name usage (according to slack) is to either directly use the name of the solr field, or to use
`#{::ActiveFedora.index_field_mapper.solr_name(work_identifier)}`

The latter might be the right approach, but it can fail is `source_identifier` is set to a field that does not need its name converted, like `id`, which gets expanded to `id_tesim` in my testing.

**Comment by bkiahstroud** [comment]
Resolved by #700
