### ISSUE TITLE
Rubocop / Bixby

### ISSUE THREAD

**Issue by geekscruff** [samvera-labs/bulkrax#70]
Rubocop and bixby are part of the bulkrax codebase, but have not been run over the code as yet. The task is to:

(To be completed by #107) 
- [x] set-up rubocop and bixby
- [x] run `rubocop -a` to autocorrect
- [x] run `rubocop --auto-gen-config` to analyse errors

(To be completed by #114 and others)
- [x] fix error or add enable / disable to skip

Note - as of 8/11/2019 rubocop would not run against bulkrax with bixby due to lots of errors; needs analysis

Part of #44

**Comment by bkiahstroud** [comment]
I can't self-assign this to me, but I'd like to tackle it @geekscruff

**Comment by orangewolf** [comment]
this was completed
