### ISSUE TITLE
Add a database index for statuses

### ISSUE THREAD

**Issue by crisr15** [samvera-labs/bulkrax#701]
# Summary

When opening a large importer with lots of statuses the request bogs down the system or can time out.  

Developers said that there is no index on statuses currently and that this should resolve it.  

# Acceptance Criteria

- [ ] a user can open any importer page without it timing out due to status.  (test with an importer of 5,000 items)
- [ ] Statuses have a an index so they can be accessed more quickly.

**Comment by ShanaLMoore** [comment]
this issue ended up not being the problem. ref PR: https://github.com/samvera-labs/bulkrax/pull/706
