### ISSUE TITLE
Continuous Integration (CI) enhancements

### ISSUE THREAD

**Issue by ghost** [samvera-labs/bulkrax#72]
## Summary 

Relevant [requirements](https://samvera.github.io/samvera_labs.html#code-requirements): 

> - uses CI (Preferably CircleCI, unless there is a compelling reason to do something else)
> - Show compatibility with current Rails versions and other dependencies, when was it last tested; note compatibility with prior versions when available. Compatibility can be specified in the gemspec(s) or verified via CI matrix.

## Acceptance Criteria

- [ ] Show compatibility with current Rails versions and other dependencies, when was it last tested; note compatibility with prior versions when available. Compatibility can be specified in the gemspec(s) or verified via CI matrix 
- [ ] Run tests against multiple versions of Hyrax 

Part of #44

**Comment by straleyb** [comment]
We've decided using github workflows across our applications so this can be closed.
