### ISSUE TITLE
Meet samvera org documentation requirements

### ISSUE THREAD

**Issue by ghost** [samvera-labs/bulkrax#73]
## Summary

See Samvera documentation requirements [here](https://samvera.github.io/samvera_labs.html#documentation-requirements). 

## Acceptance Criteria

- [x] LICENSE file, Apache 2 (or compatible)
- [x] README.md
  - [x] Up to date 
- [x] Statement of purpose
- [x] Basic install steps
  - [x] Up to date 
- [x] Identify any volatile/experimental features
  - [x] Up to date
  - [x] E.g. https://github.com/samvera-labs/bulkrax/issues/616 
- [x] How to contribute -> CONTRIBUTING.md
  - [x] Up to date
- [x] How/Who to contact for help -> push out to all gems like CONTRIBUTING.md
  - [x] Up to date
- [x] Known issues documented in github Issues tickets (not just listed in text)
- [x] Tutorial / Walkthrough / Example usage
- [x] Resolve TODO items in documents and remove them

**Optional requirements:**

- [ ] use YARD documentation conventations (as per most samvera repos)
- [ ] increase documentation coverage (maybe add an inch-ci.org badge to README)
- [ ] review and make recommendations for improving README and WIKI documentation in new ticket(s)

**Comment by orangewolf** [comment]
@alishaevn I've reviewed this list and think it is complete. Do you agree? If so, I think we can close this issue.

**Comment by alishaevn** [comment]
> @alishaevn I've reviewed this list and think it is complete. Do you agree? If so, I think we can close this issue.

certainly looks like more things are checked off than I remembered. lol. so yeah, sounds good to me.
closing!
