### ISSUE TITLE
CSV Entries and Parsers

### ISSUE THREAD

**Issue by orangewolf** [samvera-labs/bulkrax#8]
Bulkrax importer object is tied (via dropdown menu selection) to a parser. CSV work should look at [Darlingtonia](https://github.com/curationexperts/darlingtonia), [Avalon importer](https://github.com/avalonmediasystem/avalon), [Samvera bulk ingest gem](https://github.com/samvera-labs/hyrax-batch_ingest) and [bridge to Hyku importer](https://github.com/Bridge2Hyku/hybridge) for inspiration. I'd love to either pull in or replace hybridge concepts and other gems.

See CDRI importer in ATLA codebase for how a bulkraxy file importer might work. CSV should allow to import only mapped fields _or_ all fields based on a checkbox in the importer create (parser_field)

Expectation is that this task needs to be broken down in to more issues / parts.

**Comment by geekscruff** [comment]
See #13
